### PR TITLE
Mutex::~Mutex() now waits for unlock to prevent data corruption

### PR DESCRIPTION
**Pull request by celliott181**

### CODE REVIEW

**Comment by yusiwen** [comment]
I think there might be a problem to unlock a lock which has been already unlocked.
Should it be:

```
while (is_locked) unlock();
```

?

**Comment by bilash** [comment]
Thanks @yusiwen  for noticing this. I think you are right, we are unlocking twice here. Will you be able to fix in a pull request?

**Comment by celliott181** [comment]
The `while(is_locked);` is simply a cheap method to wait until the mutex is unlocked. The `unlock();` call could be considered unnecessary as once the thread passes the while loop the mutex should be guaranteed unlocked. The point of this pull request was to introduce a proper blocking call in the event the mutex is locked and asked to destruct. This is meant to mitigate a data safety issue and a possible race condition. Using `while(is_locked) unlock();` will actually defeat the block, and essentially undo the request with a heavier while() call instead of the original if() branch.

**Comment by bilash** [comment]
Yes, removing the call to unlock() in the following line will be the most straightforward way of avoiding calling unlock() twice.

**Pull request merged**
